In [2]:
%matplotlib inline  
import scipy.stats as st
import numpy as np
import matplotlib.pyplot as plt
import math
import statsmodels.api as sm
import csv

In [4]:
from numpy import genfromtxt
my_data = genfromtxt('Cauchy.csv', delimiter=',')

In [9]:
print(np.float64(my_data[1]))

77.17


In [16]:
def my_func(x,y):
    return x**2+y**2

In [19]:
x = range(-5, 5)
y = range(-10,10)

xx, yy = np.meshgrid(x, y)
results = my_func(xx, yy)

In [20]:
print(results)

[[125 116 109 104 101 100 101 104 109 116]
 [106  97  90  85  82  81  82  85  90  97]
 [ 89  80  73  68  65  64  65  68  73  80]
 [ 74  65  58  53  50  49  50  53  58  65]
 [ 61  52  45  40  37  36  37  40  45  52]
 [ 50  41  34  29  26  25  26  29  34  41]
 [ 41  32  25  20  17  16  17  20  25  32]
 [ 34  25  18  13  10   9  10  13  18  25]
 [ 29  20  13   8   5   4   5   8  13  20]
 [ 26  17  10   5   2   1   2   5  10  17]
 [ 25  16   9   4   1   0   1   4   9  16]
 [ 26  17  10   5   2   1   2   5  10  17]
 [ 29  20  13   8   5   4   5   8  13  20]
 [ 34  25  18  13  10   9  10  13  18  25]
 [ 41  32  25  20  17  16  17  20  25  32]
 [ 50  41  34  29  26  25  26  29  34  41]
 [ 61  52  45  40  37  36  37  40  45  52]
 [ 74  65  58  53  50  49  50  53  58  65]
 [ 89  80  73  68  65  64  65  68  73  80]
 [106  97  90  85  82  81  82  85  90  97]]
